name: Execute based on Features

on: [pull_request]

jobs:  
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code 
      uses: actions/checkout@v4
    - name: Get features
      uses: dorny/paths-filter@v2
      id: diff
      with:
        filters: |
          LOREMIPSUM:
            - 'lorem/**'
            - 'ipsum/**'
          DOLOR:
            - 'lorem/**'
          SITAMET:
            - 'sitamet/**'
    - name: Compose RegExp
      id: regexp
      run: echo "REGEXP='\(${{ join(fromJson(steps.diff.outputs.changes), '\|') }}\):.*\/\/'" >> $GITHUB_ENV
    - name: Execute Detox
      run: echo "detox test -c ios.sim.debug -testNamePattern=$REGEXP"