name: Check diff

on: [pull_request]

jobs:  
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code 
      uses: actions/checkout@v4
    - name: Get paths
      uses: dorny/paths-filter@v2
      id: diff
      with:
        filters: |
          LOREMS:
            - 'lorems/**'
          IPSUMS:
            - 'ipsums/**'
          DOLORS:
            - 'dolors/**'
          SITAMETS:
            - 'sitamets/**'
    - name: Compose RegExp
      id: regexp
      run: echo "REGEXP='${{ join(fromJson(steps.diff.outputs.changes), '\|') }}.*:.*\/\/'" >> "$GITHUB_OUTPUT"
    - name: Execute Detox
      env:
        REGEXP: ${{ steps.regexp.outputs.REGEXP }}
      run: echo "detox test -c ios.sim.debug -t=$REGEXP"